
#### Products ####
GET http://localhost:4040/products HTTP/1.1
###

GET http://localhost:4040/products?id=2,5,7 HTTP/1.1
###


### Get your products by catgeories
GET http://localhost:4040/products?language=German HTTP/1.1
###
GET http://localhost:4040/products?language=English&genre=science HTTP/1.1
###
// GET - OK
GET http://localhost:4040/products/3 HTTP/1.1
###
// GET for non existend -> 404 
GET http://localhost:4040/products/123123123 HTTP/1.1
###
// GET categories
GET http://localhost:4040/products/categories HTTP/1.1
###
###
// GET by science category
GET http://localhost:4040/products/categories/science HTTP/1.1
###
// GET by nonexisting category
GET http://localhost:4040/products/categories/nonexisting HTTP/1.1
###

#### Cart ####

//POST add {productId} and {userId} to {cartId}
POST http://localhost:4040/carts HTTP/1.1
content-type: application/json

{
  "userId": 1,
  "productId": 1,
  "cartId": 1
}

###

//DELETE {productId} for {userID} in {cartId}
DELETE http://localhost:4040/carts/1 HTTP/1.1
content-type: application/json

{
  "userId": 1,
  "productId": 1
}
###

//DELETE for wrong user id => error message
DELETE http://localhost:4040/carts/1 HTTP/1.1
content-type: application/json

{
  "userId": 42,
  "productId": 1
}

###

//GET cart by {cartId}
GET http://localhost:4040/carts/1 HTTP/1.1

###


// GET ALL USERS DETAILS
GET http://localhost:4040/users HTTP/1.1
###

//GET SPECIFIC USERID
// create customer
POST http://localhost:4040/users HTTP/1.1
content-type: application/json

{"id":20, "email": "AanaPeterson@gmail.com","firstName": "Ana Peterson","lastName": "Ana Peterson", "password":"ana@112"}
###

// test user login
POST http://localhost:4040/login HTTP/1.1
content-type: application/json

{"email": "AnaPeterson@gmail.com","password":"ana@112"}
###
// get user by id
GET http://localhost:4040/users/4 HTTP/1.1
###

// update user
PUT  http://localhost:4040/users/4 HTTP/1.1
content-type: application/json

{"id":5, "email": "baba123@gmail.com", "firstName": "babavaraprasadreddy","lastName": "pingili", "password":"baba@199797"}
###

// delete user
DELETE  http://localhost:4040/users/5 HTTP/1.1

###