
// products
GET http://localhost:3000/products HTTP/1.1
###
// GET - OK
GET http://localhost:3000/products/3 HTTP/1.1
###
// GET for non existend -> 404 
GET http://localhost:3000/products/123123123 HTTP/1.1
###
// GET categories
GET http://localhost:3000/products/categories HTTP/1.1
###
// GET by novel category
GET http://localhost:3000/products/categories/novel HTTP/1.1
###
// GET by science category
GET http://localhost:3000/products/categories/science HTTP/1.1
###
// GET by nonexisting category
GET http://localhost:3000/products/categories/nonexisting HTTP/1.1
###
// GET ALL USERS DETAILS
GET http://localhost:3000/users HTTP/1.1
###

//GET SPECIFIC USERID
// create customer
POST http://localhost:3000/users HTTP/1.1
content-type: application/json
{"userid":3, "email": "AnaPeterson@gmail.com","firstName": "Ana Peterson","lastName": "Ana Peterson", "password":"ana@112"}
###

// get user by id
GET http://localhost:3000/users/1 HTTP/1.1
###

// update user
PUT  http://localhost:3000/users/1 HTTP/1.1
content-type: application/json

{"userid":15, "email": "baba123@gmail.com", "firstName": "babavaraprasadreddy","lastName": "pingili", "password":"baba@199797"}
###

// delete user
DELETE  http://localhost:3000/users/2 HTTP/1.1

###