
#### Products ####
GET http://localhost:3000/products HTTP/1.1
###
// GET - OK
GET http://localhost:3000/products/3 HTTP/1.1
###
// GET for non existend -> 404 
GET http://localhost:3000/products/123123123 HTTP/1.1
###
// GET categories
GET http://localhost:3000/products/categories HTTP/1.1
###
// GET by novel category
GET http://localhost:3000/products/categories/novel HTTP/1.1
###
// GET by science category
GET http://localhost:3000/products/categories/science HTTP/1.1
###
// GET by nonexisting category
GET http://localhost:3000/products/categories/nonexisting HTTP/1.1
###

#### Cart ####

//POST create cart for userID - /cart/:userId
POST http://localhost:3000/cart/1 HTTP/1.1
###

//POST add product for userID - /cart/:userId/:productId
POST http://localhost:3000/cart/1/1 HTTP/1.1
###

//DELETE product for userID - /cart/:userId/:productId
DELETE http://localhost:3000/cart/1/1 HTTP/1.1
###

//GET cart by userID - /cart/:userId
GET http://localhost:3000/cart/1 HTTP/1.1
###